

---
title: "Análisis comparativo de la situación "
subtitle: "ENPOVE"
date: "2022"
author: ACNUR
output:
  unhcrdown::html_page:
    toc: true
    toc_depth: 2
    toc_float: true
---

## Introducción

:::{.lead}
 highlight
:::

 
```{r}
knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE, message = FALSE, warning = FALSE, fig.height = 8, fig.width = 9) 
```

```{r}
library(officedown)
library(unhcrthemes)
library(fontawesome)
library(haven)
library(dplyr)
library(scales)
library(tidyverse)
 
# turn off the automatic use of showtext functionality, so that the dml function can works properly
showtext::showtext_auto(FALSE)
## Reference #####
# https://martinctc.github.io/blog/working-with-spss-labels-in-r/
```


```{r}
# install.packages("devtools")
#devtools::install_github('yng-me/mpindex')

library(mpindex)

# ----------------------------------
# Load MPI specs from the built-in specs file
specs_file <- system.file("extdata", "global-mpi-specs.csv", package = "mpindex")
mpi_specs <- define_mpi_specs(specs_file,
  .poverty_cutoffs = c(1/3, 0.2, 0.8),
  .uid = 'uuid',
  .aggregation = 'class' )
options(mpi_specs = mpi_specs)
# `.unit_of_analysis`, `.source_of_data`, and `.names_separator` are merely used for auto labels when generating the output later.
```

```{r, echo=F}
read.csv(specs_file) |> 
  gt::gt() |> 
  gt::tab_header(
    title = 'Global MPI – Dimensions, Indicators, Deprivation Cutoffs, and Weights'
  ) |> 
  gt::tab_options(
    table.width = '100%',
    table.font.size = 12,
  ) |> 
  gt::tab_footnote('Source: Alkire, S., Kanagaratnam, U. and Suppa, N. (2020). ‘The global Multidimensional Poverty Index (MPI): 2020 revision’, OPHI MPI Methodological Note 49, Oxford Poverty and Human Development Initiative, University of Oxford.')
```

# Household 

```{r  df_household}
df_household <- read_sav(here::here("data-raw","ENPOVE2022_V_100 Características de la vivienda y del hogar.sav"))

# names(df_household)
# df_household |> dplyr::select(CIUDAD) |> dplyr::distinct() |> dplyr::pull()

## Explore all content
#df_household |>  sjPlot::view_df()

df_householda <- df_household 

######## CONSTRUIR VARIABLE UBIGEO
df_household <- df_household  |>
  mutate(CCDD = ifelse(nchar(CCDD) < 2, paste0("0", CCDD), CCDD))

df_household <- df_household  |>
  mutate(CCPP = ifelse(nchar(CCPP) < 2, paste0("0", CCPP), CCPP))

df_household <- df_household  |>
  mutate(CCDI = ifelse(nchar(CCDI) < 2, paste0("0", CCDI), CCDI))

df_household <- df_household  |>
  mutate(Ubigeo = paste0(CCDD, CCPP, CCDI))


######## CONSTRUIR UN ID PARA HOGARES
df_household <- df_household  |>
  mutate(uuid = paste0(CONGLOMERADO, NSELV, NHOGAR))  |>
  mutate(class = CIUDAD)
 

######## DEPURACIÓN DE FILAS 
#### Filtramos fuera del análisis las viviendas donde no vivían personas de Venezuela*.
df_household <- df_household  |>
  filter(P15 == 1)
#### Borramos las filas donde la encuesta no llegó a su fin
df_household <- df_household  |>
  filter(RESFIN <3)

##### Data Analysis ########################################
#  'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1

######    DIMENSIÓN 3: SERVICIOS PÚBLICOS ####################

##### INDICADOR 1:PORCENTAJE DE HOGARES CON NECESIDADES DE AGUA

##Necesidad de agua = Hogares que no cuentan con acceso a agua a través de red pública dentro de la vivienda
# table(df_household$P108_1, useNA = "ifany")

df_household <- df_household |>
          dplyr::mutate(ind03_01 = dplyr::case_when(
            P108_1 == 1 ~ 1,   TRUE ~ 0   ) )
df_household$ind03_01  <- labelled::labelled(df_household$ind03_01,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 1:PORCENTAJE DE HOGARES CON NECESIDADES DE AGUA")

##Necesidad de agua = Hogares que no cuentan con acceso a agua a través de red pública
df_household <- df_household |>
          dplyr::mutate(ind03_01v2 = dplyr::case_when(
            P108_1 < 3 ~ 1,   TRUE ~ 0   ) )
df_household$ind03_01v2  <- labelled::labelled(df_household$ind03_01v2,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 1:PORCENTAJE DE HOGARES CON NECESIDADES DE AGUA v2")


##### INDICADOR 2:PORCENTAJE DE HOGARES CON NECESIDADES DE SANEAMIENTO

##Necesidad de saneamiento = Hogares que no cuentan con conexión a desagüe dentro de la vivienda 
df_household <- df_household |>
          dplyr::mutate(ind03_02 = dplyr::case_when(
            P108_2 == 1 ~ 1,   TRUE ~ 0   ) )
df_household$ind03_02  <- labelled::labelled(df_household$ind03_02,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 2:PORCENTAJE DE HOGARES CON NECESIDADES DE SANEAMIENTO")

##Necesidad de saneamiento = Hogares que no cuentan con conexión a desagüe
df_household <- df_household |>
          dplyr::mutate(ind03_02v2 = dplyr::case_when(
            P108_2 < 3 ~ 1,   TRUE ~ 0   ) )
df_household$ind03_02v2  <- labelled::labelled(df_household$ind03_02v2,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 2:PORCENTAJE DE HOGARES CON NECESIDADES DE SANEAMIENTO v2")


##### INDICADOR 3:PORCENTAJE DE HOGARES CON NECESIDADES DE ELECTRICIDAD

##Necesidad de electricidad = Hogares que no cuentan con acceso a alumbrado/electricidad
df_household$ind03_03 <- NA
df_household[df_household$P108_3 > 1,"ind03_03"]<- 0 
df_household$ind03_03[is.na(df_household$ind03_03)] <- 1
#df_household$ind03_03 <- as.numeric(df_household$ind03_03)
df_household$ind03_03  <- labelled::labelled(df_household$ind03_03,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 3:PORCENTAJE DE HOGARES CON NECESIDADES DE ELECTRICIDAD")


#######    DIMENSIÓN 4: CONDICIONES DE VIVIENDA ####################

##### INDICADOR 1: ADEQUATE FLOORING

## Tipo de Piso## 
#unimproved floor when earth,sand,clay,mud, dung or other, as in UNHCR RMS indicator DWE02
# Se utilizó los hogares que tengan pisos de: 6) Tierra o 7) Otro material
df_household$ind04_01 <- NA
df_household[df_household$P104 == 6 | df_household$P104 == 7, "ind04_01"] <- 0                             
df_household$ind04_01[is.na(df_household$ind04_01)] <- 1
#df_household$ind04_01 <- as.numeric(df_household$ind04_01)
df_household$ind04_01  <- labelled::labelled(df_household$ind04_01,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 1: ADEQUATE FLOORING")


##### INDICADOR 2: ADEQUATE WALLS

## Tipo de Pared## 

#improved wall: cement,stone,bricks,cement blocks, covered adobe, wood planks, as in UNHCR RMS indicator DWE04. 
#Se utilizó los hogares que tengan paredes de: 4) Tapia; 5) Quincha (caña con barro); 6) Piedra con barro; 7) Madera (pona, tornillo, etc.); 8) Triplay/calamina/estera y 9) Otro material
df_household$ind04_02 <- NA
df_household[df_household$P102 > 3, "ind04_02"] <- 0                             
df_household$ind04_02[is.na(df_household$ind04_02)] <- 1
#df_household$ind04_02 <- as.numeric(df_household$ind04_02)
df_household$ind04_02  <- labelled::labelled(df_household$ind04_02,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 2: ADEQUATE WALLS")

#Se utilizó los hogares que tengan paredes de: 2) Piedra, sillar con cal o cemento; 3) Adobe; 4) Tapia; 5) Quincha (caña con barro); 6) Piedra con barro; 7) Madera (pona, tornillo, etc.); 8) Triplay/calamina/estera y 9) Otro material

df_household$ind04_02v2 <- NA
df_household[df_household$P102 > 1, "ind04_02v2"] <- 0                             
df_household$ind04_02v2[is.na(df_household$ind04_02v2)] <- 1
#df_household$ind04_02v2 <- as.numeric(df_household$ind04_02v2)
df_household$ind04_02v2  <- labelled::labelled(df_household$ind04_02v2,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 2: ADEQUATE WALLS v2")


##### INDICADOR 3: ADEQUATE ROOFS

## Tipo de Techo## 

#unimproved roof all options except metal,wood,ceramic tiles, cement, roofing shingles/sheets, as in UNHCR RMS indicator DWE03.

#Se utilizó los hogares que tengan techos de: 5) Caña o estera con torta de barro o cemento; 6) Triplay/estera/carrizo; 7) Paja, hojas de palmera, etc y 8) Otro material
df_household$ind04_03 <- NA
df_household[df_household$P103 > 4, "ind04_03"] <- 0                             
df_household$ind04_03[is.na(df_household$ind04_03)] <- 1
#df_household$ind04_03 <- as.numeric(df_household$ind04_03)
df_household$ind04_03  <- labelled::labelled(df_household$ind04_03,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 3: ADEQUATE ROOFS")


##### INDICADOR 4: OVERCROWDING 

##Hacinamiento

# Calculate crowding index - overcrowded when more than 2.5 persons per room (using number of rooms in the Household (P105))
df_household <-  df_household  |>
  dplyr::mutate(crowding=P15_N/P105 )  |>
  dplyr::mutate(ind04_04= dplyr::case_when( 
    crowding< 2.5 ~ 1, 
    TRUE ~ 0)
  )
df_household$ind04_04  <- labelled::labelled(df_household$ind04_04,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 4: OVERCROWDING ")


# Calculate crowding index - overcrowded when more than 2.5 persons per room (using number of bedrooms in the Household (P106))
df_household <-  df_household  |>
  mutate(P106vf=case_when(
    P106 > 0 ~ P106, TRUE ~ P105))  |>
  mutate(crowdingv2=P15_N/P106vf
  )  |>
  mutate(ind04_04v2 = case_when(
    crowdingv2< 2.5 ~ "1", TRUE ~ "0")
  )


##### INDICADOR 5: COOKING FUEL
#The household cooks with dung, wood, charcoal or coal
df_household$ind04_05 <- NA
df_household[df_household$P109 >3, "ind04_05"] <- 0                             
df_household$ind04_05[is.na(df_household$ind04_05)] <- 1
#df_household$ind04_05 <- as.numeric(df_household$ind04_05)
df_household$ind04_05  <- labelled::labelled(df_household$ind04_05,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 5: COOKING FUEL")


##### INDICADOR 6: ASSETS

#The household does not own a car or truck and does not own more than one of the following assets: radio, television, telephone, computer, animal cart, bicycle, motorbike or refrigerator

#Adaptamos el cálculo de este indicador. Si los hogares no tienen más de uno de los siguientes activos: 1) Radio, 2) TV, 6) Teleofono celular or 7) Telefono fijo, 5) Computadora/laptop/tableta, 9) Refrigeradora/congeladora

#PREPROCESSING
df_household <- df_household  |>
  mutate(P110_1 = ifelse(P110_1==2,0,P110_1)) |>
  mutate(P110_2 = ifelse(P110_2==2,0,P110_2)) |>
  mutate(P110_3 = ifelse(P110_3==2,0,P110_3)) |>
  mutate(P110_4 = ifelse(P110_4==2,0,P110_4)) |>
  mutate(P110_5 = ifelse(P110_5==2,0,P110_5)) |>
  mutate(P110_6 = ifelse(P110_6==2,0,P110_6)) |>
  mutate(P110_7 = ifelse(P110_7==2,0,P110_7)) |>
  mutate(P110_8 = ifelse(P110_8==2,0,P110_8)) |>
  mutate(P110_9 = ifelse(P110_9==2,0,P110_9)) |>
  mutate(P110_10 = ifelse(P110_10==2,0,P110_10)) |>
  mutate(P110_11 = ifelse(P110_11==2,0,P110_11)) |>
  mutate(P110_12 = ifelse(P110_12==2,0,P110_12)) |>
  mutate(P110_13 = ifelse(P110_13==2,0,P110_13))

#creación de variable tenencia de algún tipo de teléfono (fijo o móvil)
df_household$P110_14 <- NA
df_household[df_household$P110_6 == 0 & df_household$P110_7 == 0, "P110_14"] <- 0     
df_household$P110_14[is.na(df_household$P110_14)] <- 1
df_household$P110_14<- as.numeric(df_household$P110_14)

#Creación de un indicador compuesto que resume la tenencia de: 1) TV; 5) Computadora / laptop / tableta; 14) Teléfono (fijo o móvil); 8) Radio; 9) Refrigeradora/congeladora
df_household <- df_household  |>
  mutate(P110=(P110_1 + P110_5 + P110_14 + P110_8 + P110_9))

#Household does not owns 3 or more items
df_household$ind04_06 <- NA
df_household[df_household$P110 <=2, "ind04_06"] <- 0                            
df_household$ind04_06[is.na(df_household$ind04_06)] <- 1
#df_household$ind04_06 <- as.numeric(df_household$ind04_06)   
df_household$ind04_06  <- labelled::labelled(df_household$ind04_06,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "Household does not owns 3 or more items") 

#Household does not owns 2 or more items
df_household$ind04_06v2 <- NA
df_household[df_household$P110 <=3, "ind04_06v2"] <- 0                          
df_household$ind04_06v2[is.na(df_household$ind04_06v2)] <- 1
# df_household$ind04_06v2 <- as.numeric(df_household$ind04_06v2)    
df_household$ind04_06v2  <- labelled::labelled(df_household$ind04_06v2,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "Household does not owns 2 or more items")   

##### INDICADOR 7: TIPO DE VIVIENDA

## Tipo de vivienda## 
#Only apartment and house, as in UNHCR RMS indicator DWE01
#Se utilizó los hogares cuyo tipo de vivienda no sean: 1) Casa independiente o 2) Departamento en edificio
df_household$ind04_07 <- NA
df_household[df_household$P101 == 1 | df_household$P101 == 2, "ind04_07"] <- 1                             
df_household$ind04_07[is.na(df_household$ind04_07)] <- 0
#df_household$ind04_07 <- as.numeric(df_household$ind04_07)   
df_household$ind04_07  <- labelled::labelled(df_household$ind04_07,
  labels = c( 'Hay necesidad' = 0, 'No hay necesidad/vulnerabilidad' =1 ),
  label = "INDICADOR 7: TIPO DE VIVIENDA")   


```


```{r HogarViz}

cross <- c("CIUDAD")
crosslab <- "CIUDAD"
# dput(names(df_household))
data <- df_household |>
        dplyr::select( CIUDAD, factorfinal , 
#                        P21, 
# P101, P102, P103, P104, P105, P106, P107, P108_1, 
# P108_2, P108_3, P108_4, P109, P110_1, P110_2, P110_3, 
# P110_4, P110_5, P110_6, P110_7, P110_8, P110_9, P110_10, 
# P110_11, P110_12, P110_13, P111, P111A, P112_1, P112_2, 
# P112_3, P112_4, P112_5, P112_6, P112_7, P112_8
 SEGMENTO,  Ubigeo,   uuid,
ind03_01,  ind03_01v2, 
ind03_02,  ind03_02v2,
ind03_03,    
ind04_01,  
ind04_02,  ind04_02v2, 
ind04_03,  crowding,  
ind04_04,    
P106vf, crowdingv2, ind04_04v2, 
ind04_05,  P110_14, # P110,        
ind04_06,  ind04_06v2, ind04_07
)
# retrieve value and variable labels
#data.var <- sjlabelled::get_label(data)
data.val <-sjlabelled::get_labels(data)
weight <- as.vector(data$factorfinal)

for (i in 6:ncol(data)) {
  # i <-5
  var <- names(data)[i]
  varlab <- sjlabelled::get_label(data[i])
  type <- ifelse(lengths(data.val[i]) > 0, 
                 paste0(" -- Categoric Variable"), 
                 paste0(" -- Numeric Variable"))
  #cat(paste0(i, "-", var, "-" ,varlab,"-" ,type,"\n\n"))
  t <- as.data.frame(table(data[ , i] ))
  if(nrow(t)>1 ) {
    ## test if it is numeric or categoric variable
    if(lengths(data.val[i]) > 0) {
      # if(nrow(t)< 8) {
      p <-   sjPlot::plot_xtab(x= data[[i]],
                               grp = data[[cross]],
                               type = "bar",
                               weight.by = weight,
                               # bar.pos = "stack",
                              # sort.frq =  "asc",
                               #show.ci = TRUE,
                               wrap.labels = 40,
                               show.total = FALSE,
                               show.summary = FALSE,
                               show.prc = FALSE,
                               summary.pos = "r",
                               coord.flip = TRUE) +
        
        unhcrthemes::theme_unhcr(font_size = 12,
                                # grid = "Y", axis = "X", axis_title = "y"
                                  grid = "X",  axis = "Y",  axis_title = "X"
                                 ) + 
        ## and the chart labels
        labs(title = stringr::str_wrap(paste0(varlab) , 70),
             subtitle = paste0("Cruzado con ", crosslab),
             x = "",
             y = "",
             caption = "Fuente:  ENPOVE, https://proyectos.inei.gob.pe/microdatos/")
    } else {
      
      
      ## Print an histogram
      p <-   sjPlot::plot_grpfrq(var.cnt = data[[i]],
                                 var.grp = data[[cross]],
                                 type = "bar",
                                 weight.by = weight,
                                 # sort.frq =  "asc",
                                 # bar.pos = "stack",
                                 wrap.labels = 40,
                                 show.summary = FALSE,
                                 show.prc = FALSE,
                                 show.values = FALSE,
                                 show.n = FALSE) +
        
        unhcrthemes::theme_unhcr(font_size = 12,
                                 grid = "Y", 
                                 axis = "X", 
                                 axis_title = FALSE) + 
        ## and the chart labels
        labs(title = stringr::str_wrap(paste0(varlab) , 70),
             subtitle = paste0("Cruzado con ",crosslab),
             x = "",
             y = "",
             caption = "Fuente: ENPOVE, https://proyectos.inei.gob.pe/microdatos/")
    }
    print(p)
    #ggsave( paste0("plot/",cross," - ", i, "-",var, ".png"),  plot =  p, device = "png", width = 24, height = 16, units = "cm")
  } else {
    cat(paste0("Un solo valor para ", var, "\n"))
  }
}

```
 
# Household Roster

```{r df_household_roster, eval=FALSE, include=FALSE}
df_household_roster <- read_sav(here::here("data-raw","ENPOVE2022_V_200-300-400-500-600-700-800.sav"))
#df_household_roster |>  sjPlot::view_df()
df_household_rostera <- df_household_roster

######## CONSTRUIR VARIABLE UBIGEO
df_household_roster <- df_household_roster  |>
  mutate(CCDD = ifelse(nchar(CCDD) < 2, paste0("0", CCDD), CCDD))

df_household_roster <- df_household_roster  |>
  mutate(CCPP = ifelse(nchar(CCPP) < 2, paste0("0", CCPP), CCPP))

df_household_roster <- df_household_roster  |>
  mutate(CCDI = ifelse(nchar(CCDI) < 2, paste0("0", CCDI), CCDI))

df_household_roster <- df_household_roster  |>
  mutate(Ubigeo = paste0(CCDD, CCPP, CCDI))


######## CONSTRUIR UN ID PARA HOGARES
df_household_roster <- df_household_roster  |>
  mutate(uuid = paste0(CONGLOMERADO, NSELV, NHOGAR))|>
  mutate(class = CIUDAD)

######## CONSTRUIR UN ID PARA PERSONAS
df_household_roster <- df_household_roster  |>
  mutate(id_persona = paste0(uuid, P200_N))

######## DEPURACIÓN DE FILAS 
#### Filtramos fuera del análisis las viviendas donde no vivían personas de Venezuela*.
df_household_roster <- df_household_roster  |>
  filter(P15 ==1)

#### Borramos las filas donde la encuesta no llegó a su fin
df_household_roster <- df_household_roster  |>
  filter(RESFIN <3)

#### Filtramos fuera del análisis las personas que no migraron de Venezuela*.
df_household_roster <- df_household_roster  |>
  filter(P208 ==1)


#### Data Analysis ########################################
# 0: Hay necesidad
# 1: No hay necesidad/vulnerabilidad

###############    DIMENSIÓN 1: SALUD ####################

##### INDICADOR 1: Afiliación a seguro de salud
df_household_roster$IND04_08 <- NA
df_household_roster$IND04_08[df_household_roster$P401_5 == 1] <- 1
df_household_roster$IND04_08[is.na(df_household_roster$IND04_08)] <- 0
df_household_roster$IND04_08 <- as.numeric(df_household_roster$IND04_08)

##### INDICADOR 2: Access to health care services when needed (en el último mes) P405<7 & P406>4

df_household_roster$P406 <- NA
df_household_roster$P406[df_household_roster$P406_1 == 1 | df_household_roster$P406_2 == 1 | df_household_roster$P406_3 == 1 | df_household_roster$P406_4 == 1] <- 0
df_household_roster$P406[is.na(df_household_roster$P406)] <- 1
df_household_roster$P406 <- as.numeric(df_household_roster$P406)

df_household_roster$IND04_09 <- NA
df_household_roster$IND04_09[df_household_roster$P405_7 == 0 & df_household_roster$P406==1 ] <- 1
df_household_roster$IND04_09[is.na(df_household_roster$IND04_09)] <- 0
df_household_roster$IND04_09 <- as.numeric(df_household_roster$IND04_09)


## crear sum de indicadores, hay manera más eficaz de hacerlo??

df_household_roster1 <- df_household_roster  |>
  group_by(uuid)  |>
  summarise(sum_IND04_08 = sum(IND04_08,na.rm = TRUE ))

df_household_roster2 <- df_household_roster  |>
  group_by(uuid)  |>
  summarise(sum_IND04_09 = sum(IND04_09,na.rm = TRUE ))

df_household_roster <- merge(df_household_roster, df_household_roster1, by = "uuid")
df_household_roster <- merge(df_household_roster, df_household_roster2, by = "uuid")

df_household_roster<- df_household_roster  |>
  group_by(uuid)  |>
  mutate(IND04_08_vf = sum_IND04_08 / n())  |>
  mutate(IND04_09_vf = sum_IND04_09 / n())


##################    DIMENSIÓN 2: EDUCACIÓN ####################

##### INDICADOR 1: Personas de 18 a más años de edad tienen último nivel de estudios Educación Media Diversificada Completa/Secundaria completa
#P205 > 17 & ((P501 | P501B)  < 6

df_household_roster$IND02_01 <- NA
df_household_roster$IND02_01[df_household_roster$P205_A > 17 & (df_household_roster$P501 < 6 | df_household_roster$P501B < 6)] <- 1
df_household_roster$IND02_01[is.na(df_household_roster$IND02_01)] <- 0
df_household_roster$IND02_01 <- as.numeric(df_household_roster$IND02_01)

##### INDICADOR 2: Asistencia a la escuela P205 < 18 & no asiste

df_household_roster$IND02_02 <- NA
df_household_roster$IND02_02[(df_household_roster$P205_A < 18 & df_household_roster$P205_A > 2) & df_household_roster$P506 != 1] <- 1 #hay necesdidad
df_household_roster$IND02_02[is.na(df_household_roster$IND02_02)] <- 0
df_household_roster$IND02_02 <- as.numeric(df_household_roster$IND02_02)


## crear sum de indicadores, hay manera más eficaz de hacerlo??

df_household_roster3 <- df_household_roster  |>
  group_by(uuid)  |>
  summarise(sum_IND02_01 = sum(IND02_01,na.rm = TRUE ))

df_household_roster4 <- df_household_roster  |>
  group_by(uuid)  |>
  summarise(sum_IND02_02 = sum(IND02_02,na.rm = TRUE ))

df_household_roster <- merge(df_household_roster, df_household_roster3, by = "uuid")
df_household_roster <- merge(df_household_roster, df_household_roster4, by = "uuid")

df_household_roster<- df_household_roster  |>
  group_by(uuid)  |>
  mutate(IND02_01_vf = sum_IND02_01 / n())  |>
  mutate(IND02_02_vf = sum_IND02_02 / n())


################    DIMENSIÓN 0: POBREZA MONETARIA ####################
## crear ubigeo chamba
df_household_roster$P625A_COD_DEPA <- as.character(df_household_roster$P625A_COD_DEPA)
df_household_roster$P625_COD_PROV <- as.character(df_household_roster$P625_COD_PROV)
df_household_roster$P625_COD_DIST <- as.character(df_household_roster$P625_COD_DIST)

df_household_roster <- df_household_roster  |>
  mutate(P625A_COD_DEPA = ifelse(nchar(P625A_COD_DEPA) < 2, paste0("0", P625A_COD_DEPA), P625A_COD_DEPA))

df_household_roster <- df_household_roster  |>
  mutate(P625_COD_PROV = ifelse(nchar(P625_COD_PROV) < 2, paste0("0", P625_COD_PROV), P625_COD_PROV))

df_household_roster <- df_household_roster  |>
  mutate(P625_COD_DIST = ifelse(nchar(P625_COD_DIST) < 2, paste0("0", P625_COD_DIST), P625_COD_DIST))

df_household_roster <- df_household_roster  |>
  mutate(Ubigeo_Trabajo = case_when(
    P625==1 ~ Ubigeo,
    P625==2 ~ paste0(P625A_COD_DEPA, P625_COD_PROV, P625_COD_DIST))
    )

## crear promedio de horas trabajadas
df_household_roster$P625A_COD_DEPA <- as.character(df_household_roster$P615_T)
df_household_roster$P625_COD_PROV <- as.character(df_household_roster$P616)
df_household_roster$P625_COD_PROV <- as.character(df_household_roster$P616A)

df_household_roster <- df_household_roster  |>
  mutate(HORAS_TRABAJADAS_PROMEDIO = case_when(
    P616==1 ~ P615_T,
    P616==2 ~ P616A)
    ) 

########## SCRIPT INGRESO TOTAL
## INGRESO EN DINERO 
df_household_roster <- df_household_roster  |>
  mutate(M622_1 = case_when(
    P621==1 ~ P622_1*30,
    P621==2 ~ P622_1*4.33,
    P621==3 ~ P622_1*2,
    P621==4 ~ P622_1*1,
    TRUE ~ 0)
    ) 

## INGRESO EN ESPECIE
df_household_roster <- df_household_roster  |>
  mutate(M622_2 = case_when(
    P621==1 ~ P622_2*30,
    P621==2 ~ P622_2*4.33,
    P621==3 ~ P622_2*2,
    P621==4 ~ P622_2*1,
    TRUE ~ 0)
    )  
  
df_household_roster$P623_1 <- as.numeric(df_household_roster$P623_1)
df_household_roster$P623_2 <- as.numeric(df_household_roster$P623_2)
df_household_roster$P624_1 <- as.numeric(df_household_roster$P624_1)
df_household_roster$P624_2 <- as.numeric(df_household_roster$P624_2)

## crear ingreso total  
df_household_roster$INGTOT <- df_household_roster$M622_1 +
                    df_household_roster$M622_2 + 
                    df_household_roster$P623_1 + 
                    df_household_roster$P623_2 + 
                    df_household_roster$P624_1 + 
                   df_household_roster$P624_2

## crear ingreso total monetario
df_household_roster$INGTOT_MONETARIO <- df_household_roster$M622_1 + df_household_roster$P623_1 + df_household_roster$P624_1 
summary(df_household_roster$INGTOT_MONETARIO)

## crear ingreso total no monetario
df_household_roster$INGTOT_NO_MONETARIO <- df_household_roster$M622_2 + df_household_roster$P623_2 + df_household_roster$P624_2
summary(df_household_roster$INGTOT_NO_MONETARIO)


################## Pobreza #########################
## generar variable Ingreso_medio_persona1 (INGTOT) + Ingreso_medio_persona2 (INGTOT Monetario)
## (INGTOT of household, divided by household members)
## en muchos casos solo hay 1 ingreso en cada hogar (los demás miembros realmente no trabajan o no llenaron el cuestionario??)

# Ingreso Household1 (INGTOT)

df_household_roster$Ingreso_hogar1 <-  ave(df_household_roster$INGTOT, df_household_roster$uuid, FUN=sum)

# Ingreso Household2 (INGTOT_Monetario)

df_household_roster$Ingreso_hogar2 <-  ave(df_household_roster$INGTOT_MONETARIO, df_household_roster$uuid, FUN=sum)

# Ingreso_medio_persona1  

df_household_roster$NSELV <- as.numeric(df_household_roster$NSELV)

df_household_roster <- df_household_roster  |>
  group_by(NSELV)  |>
  mutate(N_Personas_Hogar = n())

df_household_roster$Ingreso_Medio_Persona1 <- df_household_roster$Ingreso_hogar1/df_household_roster$N_Personas_Hogar

# Ingreso_medio_persona2  

df_household_roster$Ingreso_Medio_Persona2 <- df_household_roster$Ingreso_hogar2/df_household_roster$N_Personas_Hogar

#################### Personas debajo linea de Pobreza 2021

# INGTOT
# 
# df_household_roster$personas_debajo_linea_pobreza_2021 <- NA; 
# df_household_roster[df_household_roster$Ingreso_Medio_Persona1 <= 378, 
#           "personas_debajo_linea_pobreza_2021"] <- 1                             
# df_household_roster$personas_debajo_linea_pobreza_2021[is.na(df_household_roster$personas_debajo_linea_pobreza_2021)] <- 2
# unique(df_household_roster[,'personas_debajo_linea_pobreza_2021'])
# 
# df_household_roster  |> 
#   group_by(personas_debajo_linea_pobreza_2021)  |> 
#   count(personas_debajo_linea_pobreza_2021)
# 
# # ING Monetario
# 
# df_household_roster$personas_debajo_linea_pobreza_2021_2 <- NA; 
# df_household_roster[df_household_roster$Ingreso_Medio_Persona2 <= 378, "personas_debajo_linea_pobreza_2021_2"] <- 1                             
# df_household_roster$personas_debajo_linea_pobreza_2021_2[is.na(df_household_roster$personas_debajo_linea_pobreza_2021_2)] <- 2
# unique(df_household_roster[,'personas_debajo_linea_pobreza_2021_2'])
# 
# ################# Personas debajo linea de Pobreza 2022
# 
# # INGTOT
# df_household_roster$personas_debajo_linea_pobreza_2022 <- NA; 
# df_household_roster[df_household_roster$Ingreso_Medio_Persona1 <= 418.5, "personas_debajo_linea_pobreza_2022"] <- 1                             
# df_household_roster$personas_debajo_linea_pobreza_2022[is.na(df_household_roster$personas_debajo_linea_pobreza_2022)] <- 2
# unique(df_household_roster[,'personas_debajo_linea_pobreza_2022'])
# 
# df_household_roster  |> 
#   group_by(personas_debajo_linea_pobreza_2022)  |> 
#   count(personas_debajo_linea_pobreza_2022)
# 
# 
# # ING Monetario
# 
# df_household_roster$personas_debajo_linea_pobreza_2022_2 <- NA; 
# df_household_roster[df_household_roster$Ingreso_Medio_Persona2 <= 418.5, "personas_debajo_linea_pobreza_2022_2"] <- 1                             
# df_household_roster$personas_debajo_linea_pobreza_2022_2[is.na(df_household_roster$personas_debajo_linea_pobreza_2022_2)] <- 2
# unique(df_household_roster[,'personas_debajo_linea_pobreza_2022_2'])
# 
# 
# 
# #################### Personas debajo linea de Pobreza extrema 2021
# 
# # INGTOT
# 
# df_household_roster$personas_debajo_linea_pobreza_extrema_2021 <- NA; 
# df_household_roster[df_household_roster$Ingreso_Medio_Persona1 <= 201, "personas_debajo_linea_pobreza_extrema_2021"] <- 1                             
# df_household_roster$personas_debajo_linea_pobreza_extrema_2021[is.na(df_household_roster$personas_debajo_linea_pobreza_extrema_2021)] <- 2
# unique(df_household_roster[,'personas_debajo_linea_pobreza_extrema_2021'])
# 
# df_household_roster  |> 
#   group_by(personas_debajo_linea_pobreza_extrema_2021)  |> 
#   count(personas_debajo_linea_pobreza_extrema_2021)
# 
# # ING Monetario
# 
# df_household_roster$personas_debajo_linea_pobreza_extrema_2021_2 <- NA; 
# df_household_roster[df_household_roster$Ingreso_Medio_Persona2 <= 378, "personas_debajo_linea_pobreza_extrema_2021_2"] <- 1                             
# df_household_roster$personas_debajo_linea_pobreza_extrema_2021_2[is.na(df_household_roster$personas_debajo_linea_pobreza_extrema_2021_2)] <- 2
# unique(df_household_roster[,'personas_debajo_linea_pobreza_extrema_2021_2'])
# 

################# Personas debajo linea de Pobreza 2022

# INGTOT
# 
# df_household_roster$personas_debajo_linea_pobreza_extrema_2022 <- NA; 
# df_household_roster[df_household_roster$Ingreso_Medio_Persona1 <= 222.5, "personas_debajo_linea_pobreza_extrema_2022"] <- 1                             
# df_household_roster$personas_debajo_linea_pobreza_extrema_2022[is.na(df_household_roster$personas_debajo_linea_pobreza_extrema_2022)] <- 2
# unique(df_household_roster[,'personas_debajo_linea_pobreza_extrema_2022'])
# 
# df_household_roster  |> 
#   group_by(personas_debajo_linea_pobreza_extrema_2022)  |> 
#   count(personas_debajo_linea_pobreza_extrema_2022)
# 
# # ING Monetario
# 
# df_household_roster$personas_debajo_linea_pobreza_extrema_2022_2 <- NA; 
# df_household_roster[df_household_roster$Ingreso_Medio_Persona2 <= 222.5, "personas_debajo_linea_pobreza_extrema_2022_2"] <- 1                             
# df_household_roster$personas_debajo_linea_pobreza_extrema_2022_2[is.na(df_household_roster$personas_debajo_linea_pobreza_extrema_2022_2)] <- 2
# unique(df_household_roster[,'personas_debajo_linea_pobreza_extrema_2022_2'])
# 
#  
# 
# ####Select variables####
# df_household_roster_final <-  df_household_roster  |> 
#   select(uuid, CCDD,DEPARTAMENTO,CCPP,PROVINCIA,CCDI,DISTRITO,CIUDAD,CONGLOMERADO,NSELV,VIVIENDA,THOGAR,NHOGAR,ESTRATO,VRESFIN,RESFIN,P15,P15_N,
#          INF_200,P200_N,P203,P204,P205_A,P205_B,P206,P207_1,P208,P401_1,P401_2,P401_3,P401_4,P401_5,P405_1,P405_2,P405_3,P405_4,P405_5,P405_6,P405_7,
#          P406_1,P406_2,P406_3,P406_4,P406_5,P406_6,P406_7,P406_8,P501,P501B,P506,P621,P622_1,P622_2,P623_1,P623_2,P623_3,P624_1,P624_2,P624_3,P624_4,
#          factorfinal,Ubigeo,id_persona,IND04_08,P406,IND04_09,sum_IND04_08,sum_IND04_09,IND04_08_vf,IND04_09_vf,IND02_01,IND02_02,sum_IND02_01,sum_IND02_02,IND02_01_vf,IND02_02_vf,
#          Ubigeo_Trabajo,HORAS_TRABAJADAS_PROMEDIO,M622_1,M622_2,INGTOT,INGTOT_MONETARIO,INGTOT_NO_MONETARIO,Ingreso_hogar1,Ingreso_hogar2,N_Personas_Hogar,
#          Ingreso_Medio_Persona1,Ingreso_Medio_Persona2)

```

# Multidimensional Poverty Index


```{r eval=FALSE, include=FALSE}

# ----------------------------------
# Create an empty list to store deprivation profile for each indicator
deprivation_profile <- list()

deprivation_profile$nutrition <- df_household_roster |>
  define_deprivation(
    .indicator = nutrition,
    .cutoff = undernourished == 1 & age < 70,
    .collapse = TRUE
  )

deprivation_profile$child_mortality <- df_household |>
  define_deprivation(
    .indicator = child_mortality,
    .cutoff = with_child_died == 1
  )

deprivation_profile$year_schooling <- df_household_roster |>
  define_deprivation(
    .indicator = year_schooling,
    .cutoff = completed_6yrs_schooling == 2,
    .collapse = TRUE
  )

deprivation_profile$school_attendance <- df_household_roster |>
  define_deprivation(
    .indicator = school_attendance,
    .cutoff = attending_school == 2 & age %in% c(5:24),
    .collapse = TRUE
  )

deprivation_profile$cooking_fuel <- df_household |>
  define_deprivation(
    .indicator = cooking_fuel,
    .cutoff = cooking_fuel %in% c(4:6, 9)
  )

deprivation_profile$sanitation <- df_household |>
  define_deprivation(
    .indicator = sanitation,
    .cutoff = toilet > 1
  )

deprivation_profile$drinking_water <- df_household |>
  define_deprivation(
    .indicator = drinking_water,
    .cutoff = drinking_water == 2
  )

deprivation_profile$electricity <- df_household |>
  define_deprivation(
    .indicator = electricity,
    .cutoff = electricity == 2
  )

deprivation_profile$housing <- df_household |>
  define_deprivation(
    .indicator = housing,
    .cutoff = roof %in% c(5, 7, 9) | 
      walls %in% c(5, 8, 9, 99) == 2 | 
      floor %in% c(5, 6, 9)
  )

deprivation_profile$assets <- df_household |>
  dplyr::mutate_at(
    dplyr::vars(dplyr::starts_with('asset_')), 
    ~ dplyr::if_else(. > 0, 1L, 0L)
  ) |>
  dplyr::mutate(
    asset_phone = dplyr::if_else(
      (asset_telephone + asset_mobile_phone) > 0,
      1L,
      0L
    )
  ) |>
  dplyr::mutate(
    with_hh_conveniences = (
      asset_tv + asset_phone + asset_computer +
        asset_animal_cart + asset_bicycle +
        asset_motorcycle + asset_refrigerator) > 1,
    with_mobility_assets = (asset_car + asset_truck) > 0
  ) |>
  define_deprivation(
    .indicator = assets,
    .cutoff = !(with_hh_conveniences & with_mobility_assets)
  )

# ----------------------------------
# Compute the MPI
mpi_result <- df_household |>
  compute_mpi(deprivation_profile)

```

